// Turns simulation results into a Markdown report for Paul.

import type { GameConfig } from '../engine/config';
import type { SimResult } from './simulate';
import type { CardStats, SimStats } from './stats';

export interface KeyMetrics {
  firstWinRate: number;
  teamAWinRate: number;
  goalEndShare: number;
  shootoutShare: number;
  injuriesPerGame: number;
  moreInjuredWinRate: number;
  upsetRate: number;
  passCatch: number;
  forwardPassCatch: number;
  avgTurns: number;
  avgGoals: number;
  drawShare: number;
  shotSuccess: number;
  shotsPerGame: number;
  tackleSuccess: number;
}

export function keyMetrics(s: SimStats): KeyMetrics {
  const decided = s.wins.first + s.wins.second;
  return {
    firstWinRate: decided ? s.wins.first / decided : NaN,
    teamAWinRate: decided ? s.wins.A / decided : NaN,
    goalEndShare: s.games ? s.reasons.goals / s.games : NaN,
    shootoutShare: s.games ? s.reasons.shootout / s.games : NaN,
    injuriesPerGame: s.games ? (s.injuries.A.hit + s.injuries.A.dirty_play + s.injuries.B.hit + s.injuries.B.dirty_play) / s.games : NaN,
    moreInjuredWinRate: s.moreInjured.games ? s.moreInjured.wins / s.moreInjured.games : NaN,
    upsetRate: s.upsets.contests ? s.upsets.weakerWon / s.upsets.contests : NaN,
    passCatch: s.contests.pass.count ? s.contests.pass.attackerWins / s.contests.pass.count : NaN,
    forwardPassCatch: s.passesTo.forward.count ? s.passesTo.forward.attackerWins / s.passesTo.forward.count : NaN,
    avgTurns: average(s.turns),
    avgGoals: s.games ? s.goals / s.games : NaN,
    drawShare: s.games ? s.wins.draws / s.games : NaN,
    shotSuccess: s.shots ? s.shotGoals / s.shots : NaN,
    shotsPerGame: s.games ? s.shots / s.games : NaN,
    tackleSuccess: s.contests.tackle.count ? s.contests.tackle.attackerWins / s.contests.tackle.count : NaN,
  };
}

export interface Target {
  label: string;
  goal: string;
  value: (m: KeyMetrics) => number;
  format: (n: number) => string;
  low: number;
  high: number;
}

export function onTarget(t: Target, n: number): boolean {
  return n >= t.low && n <= t.high;
}

/** How far a value is outside its target (0 = on target). */
export function distanceFromTarget(t: Target, n: number): number {
  return n < t.low ? t.low - n : n > t.high ? n - t.high : 0;
}

export const TARGETS: Target[] = [
  { label: 'First-player win rate (decided games)', goal: '45–55%', value: (m) => m.firstWinRate, format: pctOf, low: 0.45, high: 0.55 },
  { label: 'Team A win rate (decided games)', goal: '45–55%', value: (m) => m.teamAWinRate, format: pctOf, low: 0.45, high: 0.55 },
  { label: 'Goals per game', goal: '1–2', value: (m) => m.avgGoals, format: (n) => n.toFixed(2), low: 1, high: 2 },
  { label: 'Games drawn', goal: 'under 20%', value: (m) => m.drawShare, format: pctOf, low: 0, high: 0.1999 },
  { label: 'Average turns per game', goal: '30–50', value: (m) => m.avgTurns, format: (n) => n.toFixed(1), low: 30, high: 50 },
  { label: 'Injuries per game', goal: '2–4', value: (m) => m.injuriesPerGame, format: (n) => n.toFixed(2), low: 2, high: 4 },
  { label: 'More-injured team wins (decided games)', goal: '≥ 35%', value: (m) => m.moreInjuredWinRate, format: pctOf, low: 0.35, high: 1 },
];

export interface Experiment {
  name: string;
  description: string;
  result: SimResult;
}

export interface ReportInput {
  date: string;
  seed: number;
  config: GameConfig;
  cardSetVersion: string;
  baseline: SimResult;
  experiments: Experiment[];
  /** Suggested tuning changes, written from the numbers. */
  suggestions: string[];
}

// ---- Formatting ----

function average(values: number[]): number {
  return values.length ? values.reduce((a, b) => a + b, 0) / values.length : NaN;
}

function median(values: number[]): number {
  if (!values.length) return NaN;
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[mid]! : (sorted[mid - 1]! + sorted[mid]!) / 2;
}

function pctOf(n: number): string {
  return Number.isNaN(n) ? '—' : `${(n * 100).toFixed(1)}%`;
}

function pct(part: number, whole: number): string {
  return whole ? pctOf(part / whole) : '—';
}

function table(headers: string[], rows: (string | number)[][]): string {
  const line = (cells: (string | number)[]) => `| ${cells.join(' | ')} |`;
  return [line(headers), line(headers.map(() => '---')), ...rows.map(line)].join('\n');
}

// ---- Report ----

export function buildReport(input: ReportInput): string {
  const { baseline, config } = input;
  const s = baseline.stats;
  const m = keyMetrics(s);
  const out: string[] = [];

  out.push(`# Simulation report — ${input.date}`);
  out.push('');
  out.push(
    `${s.games} games, computer vs computer, seed ${input.seed}, ${config.lanes} lanes, ` +
    `card set ${input.cardSetVersion}, goals to win ${config.goalsToWin}. Took ${(baseline.milliseconds / 1000).toFixed(0)} s.`,
  );
  out.push('');
  out.push('Generated by `npm run sim`. Nothing in this report has been applied to the rules or cards.');
  out.push('');

  // Health
  out.push('## Health check');
  out.push('');
  const healthy = !baseline.crashes.length && !baseline.problems.length && !baseline.capped.length;
  out.push(table(['Check', 'Result'], [
    ['Crashes', baseline.crashes.length ? `❌ ${baseline.crashes.length}` : '✅ none'],
    ['Impossible states', baseline.problems.length ? `❌ ${baseline.problems.length}` : '✅ none'],
    [`Games stopped by the ${config.maxTurns}-turn cap`, baseline.capped.length ? `❌ ${baseline.capped.length}` : '✅ none'],
  ]));
  if (!healthy) {
    out.push('');
    out.push('First problems found:');
    for (const p of [...baseline.crashes, ...baseline.problems, ...baseline.capped].slice(0, 10)) out.push(`- ${p}`);
  }
  out.push('');

  // Targets
  out.push('## Targets');
  out.push('');
  out.push(table(['Measure', 'Target', 'Result', ''], TARGETS.map((t) => {
    const v = t.value(m);
    return [t.label, t.goal, t.format(v), onTarget(t, v) ? '✅' : '❌'];
  })));
  out.push('');

  // Suggestions and experiments
  if (input.suggestions.length) {
    out.push('## Suggested tuning');
    out.push('');
    for (const line of input.suggestions) out.push(line);
    out.push('');
  }
  if (input.experiments.length) {
    out.push('## What-if experiments');
    out.push('');
    out.push('Each row is the same simulation with one change. None of these changes has been made to the game.');
    out.push('');
    const rows = [{ name: 'Current rules', description: '', result: baseline }, ...input.experiments].map((e) => {
      const k = keyMetrics(e.result.stats);
      return [
        e.name, k.avgGoals.toFixed(2), k.shotsPerGame.toFixed(1), pctOf(k.shotSuccess), pctOf(k.drawShare), pctOf(k.shootoutShare),
        k.avgTurns.toFixed(1), pctOf(k.firstWinRate), pctOf(k.teamAWinRate), k.injuriesPerGame.toFixed(2), pctOf(k.moreInjuredWinRate), pctOf(k.upsetRate),
        pctOf(k.passCatch), pctOf(k.forwardPassCatch), pctOf(k.tackleSuccess),
      ];
    });
    out.push(table(['Change', 'Goals/game', 'Shots/game', 'Shots scoring', 'Draws', 'Shootouts', 'Turns', 'First player wins', 'Team A wins', 'Injuries/game', 'More-injured team wins', 'Upsets', 'Passes caught', 'Forward passes caught', 'Tackles win'], rows));
    out.push('');
    out.push('"Upsets": contests where the weaker printed card (stat, ability, injury) won anyway, thanks to spells or dice.');
    out.push('');
    for (const e of input.experiments) out.push(`- **${e.name}:** ${e.description}`);
    out.push('');
  }

  // Detailed results
  out.push('## Results');
  out.push('');
  out.push('### Who wins');
  out.push('');
  out.push(table(['', 'Games', 'Share'], [
    ['First player wins', s.wins.first, pct(s.wins.first, s.games)],
    ['Second player wins', s.wins.second, pct(s.wins.second, s.games)],
    ['Team A wins', s.wins.A, pct(s.wins.A, s.games)],
    ['Team B wins', s.wins.B, pct(s.wins.B, s.games)],
    ['Draws', s.wins.draws, pct(s.wins.draws, s.games)],
  ]));
  out.push('');

  out.push('### How games end');
  out.push('');
  out.push(table(['Ending', 'Games', 'Share'], [
    [`A team reached ${config.goalsToWin} goals`, s.reasons.goals, pct(s.reasons.goals, s.games)],
    ['Full time (cards ran out), one team ahead', s.reasons.time, pct(s.reasons.time, s.games)],
    ['Penalty shootout', s.reasons.shootout, pct(s.reasons.shootout, s.games)],
    ['Draw (shootout ran out of shooters)', s.reasons.draw, pct(s.reasons.draw, s.games)],
    ['Turn cap (bug)', s.reasons.turn_cap, pct(s.reasons.turn_cap, s.games)],
  ]));
  out.push('');

  out.push('### Length and scoring');
  out.push('');
  out.push(table(['Measure', 'Value'], [
    ['Average turns', m.avgTurns.toFixed(1)],
    ['Median turns (shortest – longest)', `${median(s.turns)} (${Math.min(...s.turns)} – ${Math.max(...s.turns)})`],
    ['Goals per game', m.avgGoals.toFixed(2)],
    ['Shots per game', (s.shots / s.games).toFixed(2)],
    ['Shots that score', pct(s.shotGoals, s.shots)],
    ['Long shots (from midfield) per game', (s.shotsFrom.midfield.count / s.games).toFixed(2)],
  ]));
  out.push('');

  out.push('### Contests');
  out.push('');
  out.push('"Attacker wins" means: the pass is caught, the tackle takes the ball, the shot or penalty scores, the hit lands, or the team choosing the faceoff lane wins it.');
  out.push('');
  out.push(`Upsets (the weaker printed card won, thanks to spells or dice): ${pct(s.upsets.weakerWon, s.upsets.contests)} of ${s.upsets.contests} contests.`);
  if (s.diceSpent) out.push(`Rolls spent per game: ${(s.diceSpent / s.games).toFixed(1)}.`);
  out.push('');
  const contestRows = (['pass', 'tackle', 'shot', 'faceoff', 'penalty', 'hit'] as const).map((k) => {
    const c = s.contests[k];
    return [k, (c.count / s.games).toFixed(1), pct(c.attackerWins, c.count)];
  });
  out.push(table(['Contest', 'Per game', 'Attacker wins'], contestRows));
  out.push('');
  out.push(table(['Pass to', 'Per game', 'Caught'], (['defense', 'midfield', 'forward'] as const).map((area) => {
    const p = s.passesTo[area];
    return [area, (p.count / s.games).toFixed(1), pct(p.attackerWins, p.count)];
  })));
  out.push('');
  out.push(table(['Passes to a forward', 'Receiver ahead or level (printed cards)', 'Caught (after dice and spells)'], (['A', 'B'] as const).map((side) => {
    const f = s.forwardPasses[side];
    return [`Team ${side}`, pct(f.aheadOrLevel, f.count), pct(f.caught, f.count)];
  })));
  out.push('');

  out.push('### Injuries');
  out.push('');
  const injuryRate = (n: number) => (n / s.games).toFixed(2);
  const hits = s.contests.hit;
  out.push(table(['Measure', 'Value'], [
    ['Injuries per game (carry-offs included)', injuryRate(s.injuries.A.hit + s.injuries.A.dirty_play + s.injuries.B.hit + s.injuries.B.dirty_play)],
    ['…suffered by Team A', injuryRate(s.injuries.A.hit + s.injuries.A.dirty_play)],
    ['…suffered by Team B', injuryRate(s.injuries.B.hit + s.injuries.B.dirty_play)],
    ['…caused by hits', injuryRate(s.injuries.A.hit + s.injuries.B.hit)],
    ['…caused by dirty plays', injuryRate(s.injuries.A.dirty_play + s.injuries.B.dirty_play)],
    ['Players carried off per game', injuryRate(s.carriedOff)],
    ['Games where a spot sat empty', `${s.gamesWithEmptySlot} (${pct(s.gamesWithEmptySlot, s.games)})`],
    ['Goals scored into an empty goal, per game', injuryRate(s.emptyGoalGoals)],
    ['Hits per game', injuryRate(hits.count)],
    ['Hits that land', pct(hits.attackerWins, hits.count)],
    ['More-injured team won (decided games with unequal injuries)', `${pct(s.moreInjured.wins, s.moreInjured.games)} of ${s.moreInjured.games}`],
  ]));
  out.push('');

  out.push('### Spells by affinity');
  out.push('');
  const totalCast = s.affinity.match.cast + s.affinity.neutral.cast + s.affinity.opposed.cast;
  out.push(table(['Affinity', 'Casts', 'Share of casts', 'Failed (opposed, non-numeric)', "Caster's side won the contest"],
    (['match', 'neutral', 'opposed'] as const).map((a) => {
      const x = s.affinity[a];
      return [a, x.cast, pct(x.cast, totalCast), pct(x.fizzled, x.cast), pct(x.contestWins, x.inContest)];
    })));
  out.push('');

  // Cards
  const cards = [...s.cards.values()];
  const perGame = (c: CardStats) => (c.played / s.games).toFixed(2);
  const winRate = (c: CardStats) => pct(c.contestWins, c.inContest);
  const spells = cards.filter((c) => c.kind === 'spell');
  const players = cards.filter((c) => c.kind !== 'spell');

  out.push('### Cards never or rarely played');
  out.push('');
  out.push('"Rarely" means fewer than once every 10 games. Spells count when cast; players count when they take part in a contest.');
  out.push('');
  const rare = cards.filter((c) => c.played / s.games < 0.1).sort((a, b) => a.played - b.played);
  if (rare.length) {
    out.push(table(['Card', 'Team or type', 'Played per game'], rare.map((c) => [`${c.name} (${c.id})`, c.role ?? c.team, perGame(c)])));
  } else {
    out.push('None.');
  }
  out.push('');

  out.push('### Spells');
  out.push('');
  out.push(table(['Spell', 'Team', 'Cast per game', "Caster's side won the contest"],
    spells.sort((a, b) => b.played - a.played).map((c) => [`${c.name} (${c.id})`, c.team, perGame(c), winRate(c)])));
  out.push('');

  out.push('<details><summary>Players (contests per game and win rate)</summary>');
  out.push('');
  // Players from the shared pool play for either team, so show their type instead.
  out.push(table(['Player', 'Team or type', 'Contests per game', 'Won'],
    players.sort((a, b) => b.played - a.played).map((c) => [`${c.name} (${c.id})`, c.role ?? c.team, perGame(c), winRate(c)])));
  out.push('');
  out.push('</details>');
  out.push('');
  return out.join('\n');
}
